name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GAR_LOCATION: europe-central2
  GKE_CLUSTER: vv-cluster-1
  GKE_ZONE: europe-central2-a
  DEPLOYMENT_NAME: pipe-line-test
  REPO: quarkus
  IMAGE: pipeline-test

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # Configure Workload Identity Federation and generate an access token.
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - uses: 'docker/login-action@v1'
        with:
          registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'

      # Get the GKE credentials so we can deploy to the cluster
      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GAR_LOCATION }}

      # Build the Docker image
      - name: Build
        shell: bash
        run: |
          ./mvnw package -Pnative -Dquarkus.native.container-build=true -Dquarkus.container-image.build=true -DexcludedGroups="db-connected-tests"
          
          pushTag=europe-central2-docker.pkg.dev/kube-403208/quarkus/$IMAGE:$GITHUB_SHA
          
          docker tag runner/$IMAGE:1.0.0-SNAPSHOT $pushTag
          
          docker image list
        
          docker push $pushTag
          
          export image_tag=$pushTag
          export IMAGE_NAME=$IMAGE
  
          envsubst < deployment.template.yml > deployment.yaml

      - name: Deploy
        run: |-
          kubectl apply -f deployment.yaml